version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hireflow_db
    environment:
      POSTGRES_USER: hireflow
      POSTGRES_PASSWORD: hireflow_password
      POSTGRES_DB: hireflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hireflow_backend
    environment:
      DATABASE_URL: postgresql://hireflow:hireflow_password@postgres:5432/hireflow
      JWT_SECRET: super_secret_production_key_hireflow
      FRONTEND_URL: http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hireflow_frontend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
