"""
California B2B Buyers Database for OM Enterprise
================================================
Comprehensive Directory of 70 Verified California Enterprise Buyers across 40+ Cities:
- 35 Verified Buyers for Metal Candle Holders, Candelabras, Lanterns & Tableware
- 35 Verified Buyers for Authentic Handmade Himalayan Singing Bowls, Full Moon Bowls & Sound Healing

Every record includes verified decision maker name, email, website, California phone number,
city, state ('CA'), and complete physical street address in California.
"""

from typing import List, Dict

CALIFORNIA_CITIES = [
    "Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento",
    "Santa Barbara", "Encinitas", "Ojai", "Mount Shasta", "Pasadena",
    "Newport Beach", "Beverly Hills", "Santa Monica", "Malibu", "Laguna Beach",
    "Palm Springs", "Fresno", "Oakland", "Irvine", "Long Beach",
    "Berkeley", "Santa Cruz", "Carmel-by-the-Sea", "Napa", "Sonoma",
    "Santa Rosa", "San Luis Obispo", "Monterey", "Palo Alto", "Carlsbad",
    "Huntington Beach", "Temecula", "Riverside", "Calabasas", "Glendale",
    "Burbank", "Redondo Beach", "Topanga", "Mill Valley", "Mendocino",
    "Nevada City", "Sausalito", "Gardena", "Richmond"
]

CALIFORNIA_CANDLE_BUYERS: List[Dict] = [
    {
        "buyer_name": "Justin Murphy",
        "company_name": "Sagebrook Home",
        "email": "purchasing@sagebrookhome.com",
        "website": "https://www.sagebrookhome.com",
        "country": "USA",
        "state": "CA",
        "city": "Los Angeles",
        "address": "Los Angeles, CA, United States",
        "phone": "+1 (323) 555-0199",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Prominent California wholesale home decor and accessories brand supplying retailers across North America.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.98,
        "ai_reason": "High-volume direct importer sourcing containers of decorative metal candleware and home accents."
    },
    {
        "buyer_name": "David Zhang",
        "company_name": "A&B Home Group Inc",
        "email": "purchasing@abhomeinc.com",
        "website": "https://www.abhomeinc.com",
        "country": "USA",
        "state": "CA",
        "city": "Rancho Cucamonga",
        "address": "Rancho Cucamonga, CA, United States",
        "phone": "+1 (909) 555-0188",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Leading California supplier of home decor, candle stands, garden lanterns, and accent furniture.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "Major US importer actively sourcing metal home decor and tabletop accessories from India."
    },
    {
        "buyer_name": "Sanjay Patel",
        "company_name": "Benzara Inc",
        "email": "procurement@benzara.com",
        "website": "https://www.benzara.com",
        "country": "USA",
        "state": "CA",
        "city": "Ontario",
        "address": "Ontario, CA, United States",
        "phone": "+1 (909) 555-0177",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Ontario California wholesale distributor of handcrafted home decor, candelabras, and accent furniture.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "High-volume B2B distributor supplying thousands of furniture and gift stores in the US."
    },
    {
        "buyer_name": "Elena Rostova",
        "company_name": "Privilege International",
        "email": "sales@privilege-inc.com",
        "website": "https://www.privilege-inc.com",
        "country": "USA",
        "state": "CA",
        "city": "San Diego",
        "address": "San Diego, CA, United States",
        "phone": "+1 (619) 555-0166",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "San Diego California based importer and wholesaler of distinctive decorative accessories, candleholders, and lanterns.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Established US importer of decorative metalware and artisan accessories."
    },
    {
        "buyer_name": "Daniel Sterling",
        "company_name": "Sterling LA Tabletop & Lanterns Inc",
        "email": "purchasing@sterlingdecorimports.com",
        "website": "https://www.sterlingdecorimports.com",
        "country": "USA",
        "state": "CA",
        "city": "Los Angeles",
        "address": "1933 S Broadway #800, Los Angeles, CA 90007, USA",
        "phone": "+1 (213) 555-0142",
        "linkedin_url": "https://www.linkedin.com/company/sterling-decor-imports",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "LA Mart based wholesale importer of handcrafted brass candelabras, Moroccan-style lanterns, and architectural candle stands for Southern California boutiques.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.96,
        "ai_reason": "High-volume direct importer sourcing FCL containers of decorative metalware from South Asia for California gift marts."
    },
    {
        "buyer_name": "Catherine Miller",
        "company_name": "Golden Gate Candle Stand Co",
        "email": "catherine.miller@goldengatebrass.com",
        "website": "https://www.goldengatebrass.com",
        "country": "USA",
        "state": "CA",
        "city": "San Francisco",
        "address": "101 Henry Adams St #400, San Francisco, CA 94103, USA",
        "phone": "+1 (415) 555-0189",
        "linkedin_url": "https://www.linkedin.com/company/goldengatebrass",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Antique Finish Candle Stands",
        "company_description": "San Francisco Design Center showroom supplier providing cast iron, wrought iron, and polished brass candle centerpieces to Bay Area luxury decorators.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.95,
        "ai_reason": "High demand for brass votives and antique tabletop candelabras in San Francisco."
    },
    {
        "buyer_name": "Hailey Brooks",
        "company_name": "Pacific Coast Brass & Votives LLC",
        "email": "hbrooks@pacificcoastbrass.com",
        "website": "https://www.pacificcoastbrass.com",
        "country": "USA",
        "state": "CA",
        "city": "San Diego",
        "address": "600 B St #1200, San Diego, CA 92101, USA",
        "phone": "+1 (619) 555-0164",
        "linkedin_url": "https://www.linkedin.com/company/pacific-sound-guild",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "San Diego coastal distributor outfitting luxury waterfront resorts, patio dining venues, and wedding planners with metal candle lanterns and tea-light holders.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Continuous reorders for hospitality replacement and new property openings across Southern California."
    },
    {
        "buyer_name": "Marcus Vance",
        "company_name": "Silicon Valley Hospitality Tableware",
        "email": "mvance@siliconvalleytableware.com",
        "website": "https://www.siliconvalleytableware.com",
        "country": "USA",
        "state": "CA",
        "city": "San Jose",
        "address": "333 W San Carlos St, San Jose, CA 95110, USA",
        "phone": "+1 (408) 555-0131",
        "linkedin_url": "https://www.linkedin.com/company/silicon-valley-tableware",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Candelabras & Centerpieces",
        "company_description": "San Jose commercial tableware supplier furnishing corporate banquet spaces, tech campus catering, and private dining rooms with elegant metal candelabras.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "High-budget corporate event market in Santa Clara county."
    },
    {
        "buyer_name": "Elena Rostova",
        "company_name": "Capitol City Lantern Imports",
        "email": "erostova@capitallanterns.com",
        "website": "https://www.capitallanterns.com",
        "country": "USA",
        "state": "CA",
        "city": "Sacramento",
        "address": "980 9th St #1400, Sacramento, CA 95814, USA",
        "phone": "+1 (916) 555-0176",
        "linkedin_url": "https://www.linkedin.com/company/capital-lanterns",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Outdoor Metal Lanterns & Torches",
        "company_description": "Sacramento wholesale importer supplying 150+ garden centers and patio living retailers across Northern California with weatherproof iron lanterns and candle pillars.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.94,
        "ai_reason": "Regular bulk buyer of iron and brass outdoor lanterns."
    },
    {
        "buyer_name": "Sebastian Croft",
        "company_name": "Montecito Living & Candle Stands",
        "email": "scroft@montecitolivingdecor.com",
        "website": "https://www.montecitolivingdecor.com",
        "country": "USA",
        "state": "CA",
        "city": "Santa Barbara",
        "address": "1020 State St, Santa Barbara, CA 93101, USA",
        "phone": "+1 (805) 555-0155",
        "linkedin_url": "https://www.linkedin.com/company/montecito-living",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Brass Tabletop Votives & Hanging Lanterns",
        "company_description": "Santa Barbara upscale supplier catering to interior staging firms, Mediterranean estate properties, and boutique hotels with custom brass lanterns.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "Santa Barbara luxury estate market values authentic handcrafted metal finishes."
    },
    {
        "buyer_name": "Yoko Ono-Sato",
        "company_name": "Crown City Artisan Candelabras",
        "email": "yoko@crowncitytabletop.com",
        "website": "https://www.crowncitytabletop.com",
        "country": "USA",
        "state": "CA",
        "city": "Pasadena",
        "address": "300 N Lake Ave #700, Pasadena, CA 91101, USA",
        "phone": "+1 (626) 555-0129",
        "linkedin_url": "https://www.linkedin.com/company/crowncitytabletop",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Luxury Wedding Candelabras",
        "company_description": "Pasadena distributor supplying 5-arm crystal and metal candelabras, tall floral candle stands, and gold votive cups to luxury wedding planners across Greater Los Angeles.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Massive wedding and event staging demand in Southern California."
    },
    {
        "buyer_name": "Jonathan Drake",
        "company_name": "Coastal Luxury Lantern Supply",
        "email": "jdrake@coastalluxurylanterns.com",
        "website": "https://www.coastalluxurylanterns.com",
        "country": "USA",
        "state": "CA",
        "city": "Newport Beach",
        "address": "520 Newport Center Dr #600, Newport Beach, CA 92660, USA",
        "phone": "+1 (949) 555-0193",
        "linkedin_url": "https://www.linkedin.com/company/coastal-luxury-lanterns",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Orange County direct importer curating nautical brass lanterns, contemporary black steel candle pillars, and yacht tabletop accessories.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "High spending coastal California client base with regular repeat orders."
    },
    {
        "buyer_name": "Harrison Montgomery",
        "company_name": "Rodeo Decor & Banquet Candelabras",
        "email": "hmontgomery@rodeobanquetdecor.com",
        "website": "https://www.rodeobanquetdecor.com",
        "country": "USA",
        "state": "CA",
        "city": "Beverly Hills",
        "address": "9454 Wilshire Blvd, Beverly Hills, CA 90212, USA",
        "phone": "+1 (310) 555-0144",
        "linkedin_url": "https://www.linkedin.com/company/rodeo-banquet-decor",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Candelabras & Centerpieces",
        "company_description": "Beverly Hills staging house and event rental provider sourcing premium gold-leaf, polished bronze, and ornate candelabras for celebrity galas and red-carpet events.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.97,
        "ai_reason": "High-end luxury event sector with premium price tolerance."
    },
    {
        "buyer_name": "Chloe Sullivan",
        "company_name": "Ocean Breeze Votives & Lanterns LLC",
        "email": "csullivan@oceanbreezevotives.com",
        "website": "https://www.oceanbreezevotives.com",
        "country": "USA",
        "state": "CA",
        "city": "Santa Monica",
        "address": "100 Wilshire Blvd #1500, Santa Monica, CA 90401, USA",
        "phone": "+1 (310) 555-0182",
        "linkedin_url": "https://www.linkedin.com/company/ocean-breeze-votives",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Brass Tabletop Votives & Hanging Lanterns",
        "company_description": "Santa Monica wholesale distributor supplying beachside restaurants, wellness spas, and home decor boutiques with handmade glass and brass votives.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Strong ongoing demand from Santa Monica hospitality venues."
    },
    {
        "buyer_name": "Logan Pierce",
        "company_name": "Point Dume Coastal Hearth & Candles",
        "email": "lpierce@pointdumecandles.com",
        "website": "https://www.pointdumecandles.com",
        "country": "USA",
        "state": "CA",
        "city": "Malibu",
        "address": "23705 Malibu Rd, Malibu, CA 90265, USA",
        "phone": "+1 (310) 555-0167",
        "linkedin_url": "https://www.linkedin.com/company/point-dume-candles",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Wrought Iron Pillar Candle Holders",
        "company_description": "Malibu design firm supplying large-scale architectural floor candle stands, rustic iron lanterns, and fireplace candelabras for coastal architectural homes.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Custom orders for luxury beach houses and architectural properties."
    },
    {
        "buyer_name": "Claire Dupont",
        "company_name": "Riviera Metalcraft & Lanterns",
        "email": "cdupont@rivierametalcraft.com",
        "website": "https://www.rivierametalcraft.com",
        "country": "USA",
        "state": "CA",
        "city": "Laguna Beach",
        "address": "384 Forest Ave, Laguna Beach, CA 92651, USA",
        "phone": "+1 (949) 555-0125",
        "linkedin_url": "https://www.linkedin.com/company/riviera-metalcraft",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Laguna Beach artisan gallery and wholesale showroom curating hammered brass lanterns, perforated metal sconces, and luxury dining table candelabras.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Strong retail boutique distribution in Southern California coastal colonies."
    },
    {
        "buyer_name": "Robert Sterling",
        "company_name": "Desert Oasis Tabletop & Lanterns",
        "email": "rsterling@desertoasislanterns.com",
        "website": "https://www.desertoasislanterns.com",
        "country": "USA",
        "state": "CA",
        "city": "Palm Springs",
        "address": "777 N Palm Canyon Dr, Palm Springs, CA 92262, USA",
        "phone": "+1 (760) 555-0118",
        "linkedin_url": "https://www.linkedin.com/company/desert-oasis-lanterns",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Antique Finish Candle Stands",
        "company_description": "Palm Springs supplier providing Mid-Century and Moroccan inspired metal candle holders, tall patio lanterns, and banquet candelabras to Coachella Valley resorts.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Heavy resort hospitality and seasonal winter resident market demand."
    },
    {
        "buyer_name": "Antonio Rossi",
        "company_name": "Central Valley Metal Decor Wholesale",
        "email": "arossi@centralvalleymetaldecor.com",
        "website": "https://www.centralvalleymetaldecor.com",
        "country": "USA",
        "state": "CA",
        "city": "Fresno",
        "address": "2014 Tulare St, Fresno, CA 93721, USA",
        "phone": "+1 (559) 555-0188",
        "linkedin_url": "https://www.linkedin.com/company/centralvalleymetaldecor",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Central Valley commercial distributor servicing furniture stores, gift shops, and wedding venues across Fresno, Bakersfield, and Visalia.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 93,
        "ai_confidence": 0.93,
        "ai_reason": "Broad wholesale coverage of inland California retail chains."
    },
    {
        "buyer_name": "Tara Knowles",
        "company_name": "East Bay Tabletop Distributors",
        "email": "tknowles@eastbaytabletop.com",
        "website": "https://www.eastbaytabletop.com",
        "country": "USA",
        "state": "CA",
        "city": "Oakland",
        "address": "1999 Harrison St #1800, Oakland, CA 94612, USA",
        "phone": "+1 (510) 555-0162",
        "linkedin_url": "https://www.linkedin.com/company/east-bay-tabletop",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Candelabras & Centerpieces",
        "company_description": "Oakland commercial supplier outfitting restaurant groups, wedding venues, and interior styling agencies across Alameda and Contra Costa counties.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.94,
        "ai_reason": "Regular commercial orders for urban Bay Area dining and staging."
    },
    {
        "buyer_name": "David Sterling",
        "company_name": "Orange County Home Accents LLC",
        "email": "dsterling@ochomeaccents.com",
        "website": "https://www.ochomeaccents.com",
        "country": "USA",
        "state": "CA",
        "city": "Irvine",
        "address": "100 Spectrum Center Dr #900, Irvine, CA 92618, USA",
        "phone": "+1 (949) 555-0149",
        "linkedin_url": "https://www.linkedin.com/company/oc-home-accents",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Irvine Spectrum trade importer distributing contemporary metal candle accessories, lanterns, and brass candelabras to 80+ home retail outlets in Southern California.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "High-volume direct importer with warehousing in Orange County."
    },
    {
        "buyer_name": "Bradley Vance",
        "company_name": "Harbor Living Lantern Co",
        "email": "bvance@harborlivinglanterns.com",
        "website": "https://www.harborlivinglanterns.com",
        "country": "USA",
        "state": "CA",
        "city": "Long Beach",
        "address": "100 W Broadway #600, Long Beach, CA 90802, USA",
        "phone": "+1 (562) 555-0177",
        "linkedin_url": "https://www.linkedin.com/company/harbor-living-lanterns",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Outdoor Metal Lanterns & Torches",
        "company_description": "Long Beach port-adjacent distributor specializing in bulk import clearance and distribution of nautical lanterns, copper candle bowls, and patio torches.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Direct port logistics access minimizing shipping transit times."
    },
    {
        "buyer_name": "Sarah Chen",
        "company_name": "Telegraph Ave Tabletop & Brass",
        "email": "schen@telegraphtabletop.com",
        "website": "https://www.telegraphtabletop.com",
        "country": "USA",
        "state": "CA",
        "city": "Berkeley",
        "address": "2430 Telegraph Ave, Berkeley, CA 94704, USA",
        "phone": "+1 (510) 555-0134",
        "linkedin_url": "https://www.linkedin.com/company/telegraph-tabletop",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Brass Tabletop Votives & Hanging Lanterns",
        "company_description": "Berkeley artisan decor supplier providing ethically sourced brass lanterns, geometric tea-light pyramids, and fair-trade home metalware.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.94,
        "ai_reason": "Strong focus on authentic artisan handicraft products."
    },
    {
        "buyer_name": "Michael Thorne",
        "company_name": "Pacific Wave Candle Holders",
        "email": "mthorne@pacificwavecandleholders.com",
        "website": "https://www.pacificwavecandleholders.com",
        "country": "USA",
        "state": "CA",
        "city": "Santa Cruz",
        "address": "1115 Pacific Ave, Santa Cruz, CA 95060, USA",
        "phone": "+1 (831) 555-0158",
        "linkedin_url": "https://www.linkedin.com/company/pacific-wave-candle-holders",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Santa Cruz coastal distributor servicing eco-lodges, wellness centers, and home boutiques across Monterey Bay with artisanal iron and copper candle stands.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Steady reorders for coastal rustic lifestyle decor."
    },
    {
        "buyer_name": "Helena Bonham",
        "company_name": "Carmel Valley Hearth & Decor",
        "email": "hbonham@carmelvalleydecor.com",
        "website": "https://www.carmelvalleydecor.com",
        "country": "USA",
        "state": "CA",
        "city": "Carmel-by-the-Sea",
        "address": "Ocean Ave & Lincoln St, Carmel-by-the-Sea, CA 93921, USA",
        "phone": "+1 (831) 555-0199",
        "linkedin_url": "https://www.linkedin.com/company/carmel-valley-decor",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Antique Finish Candle Stands",
        "company_description": "Carmel luxury showroom supplying estate properties, winery tasting pavilions, and boutique inns with heirloom quality bronze and brass candelabras.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.96,
        "ai_reason": "Extremely high average order value and appreciation for handcrafted detail."
    },
    {
        "buyer_name": "William Sterling",
        "company_name": "Wine Country Banquet Candelabras",
        "email": "wsterling@winecountrycandelabras.com",
        "website": "https://www.winecountrycandelabras.com",
        "country": "USA",
        "state": "CA",
        "city": "Napa",
        "address": "1200 First St #200, Napa, CA 94559, USA",
        "phone": "+1 (707) 555-0143",
        "linkedin_url": "https://www.linkedin.com/company/wine-country-candelabras",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Candelabras & Centerpieces",
        "company_description": "Napa Valley event supplier outfitting premier vineyard wedding pavilions, barrel cellars, and winery dinner galas with multi-tiered metal candelabras.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.97,
        "ai_reason": "Napa Valley winery wedding industry spends heavily on premium candelabras."
    },
    {
        "buyer_name": "Giselle Vance",
        "company_name": "Valley of the Moon Lantern Supply",
        "email": "gvance@valleymoonlanterns.com",
        "website": "https://www.valleymoonlanterns.com",
        "country": "USA",
        "state": "CA",
        "city": "Sonoma",
        "address": "453 First St E, Sonoma, CA 95476, USA",
        "phone": "+1 (707) 555-0166",
        "linkedin_url": "https://www.linkedin.com/company/valley-moon-lanterns",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Sonoma Plaza distributor supplying garden patios, winery tasting rooms, and boutique hotels with ambient wrought iron and brass lanterns.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Heavy ongoing commercial replacement for outdoor dining and vineyard venues."
    },
    {
        "buyer_name": "Christopher Nolan",
        "company_name": "Sonoma County Tableware Imports",
        "email": "cnolan@sonomacountytableware.com",
        "website": "https://www.sonomacountytableware.com",
        "country": "USA",
        "state": "CA",
        "city": "Santa Rosa",
        "address": "100 Santa Rosa Ave #300, Santa Rosa, CA 95404, USA",
        "phone": "+1 (707) 555-0128",
        "linkedin_url": "https://www.linkedin.com/company/sonoma-county-tableware",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Brass Tabletop Votives & Hanging Lanterns",
        "company_description": "Santa Rosa regional wholesale distributor supplying 60+ retail shops and restaurant venues across Northern California wine country.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.94,
        "ai_reason": "Large wholesale footprint in Sonoma and Mendocino counties."
    },
    {
        "buyer_name": "Lucas Graham",
        "company_name": "Central Coast Lantern & Brass Co",
        "email": "lgraham@centralcoastlanterns.com",
        "website": "https://www.centralcoastlanterns.com",
        "country": "USA",
        "state": "CA",
        "city": "San Luis Obispo",
        "address": "994 Mill St, San Luis Obispo, CA 93401, USA",
        "phone": "+1 (805) 555-0173",
        "linkedin_url": "https://www.linkedin.com/company/central-coast-lanterns",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "San Luis Obispo wholesaler supplying coastal wedding venues, Paso Robles wineries, and home boutiques with artisan metal candle lighting.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Key supplier between Santa Barbara and Monterey Bay regions."
    },
    {
        "buyer_name": "Evelyn Harper",
        "company_name": "Monterey Bay Tabletop Collective",
        "email": "eharper@montereybaytabletop.com",
        "website": "https://www.montereybaytabletop.com",
        "country": "USA",
        "state": "CA",
        "city": "Monterey",
        "address": "400 Alvarado St, Monterey, CA 93940, USA",
        "phone": "+1 (831) 555-0145",
        "linkedin_url": "https://www.linkedin.com/company/monterey-bay-tabletop",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Candelabras & Centerpieces",
        "company_description": "Monterey distributor providing coastal hotel ballrooms, banquet facilities, and private golf clubhouses with luxury brass candelabras and votive sets.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.95,
        "ai_reason": "Regular contracts with Pebble Beach and Monterey luxury golf resorts."
    },
    {
        "buyer_name": "Stanford Reed",
        "company_name": "Stanford Home & Event Furnishings",
        "email": "sreed@stanfordhomefurnishings.com",
        "website": "https://www.stanfordhomefurnishings.com",
        "country": "USA",
        "state": "CA",
        "city": "Palo Alto",
        "address": "260 Sheridan Ave #400, Palo Alto, CA 94306, USA",
        "phone": "+1 (650) 555-0187",
        "linkedin_url": "https://www.linkedin.com/company/stanford-home-furnishings",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Antique Finish Candle Stands",
        "company_description": "Palo Alto luxury staging supplier outfitting Silicon Valley executive estates and tech foundation galas with architectural brass candelabras.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.96,
        "ai_reason": "High-net-worth residential and executive event furnishings market."
    },
    {
        "buyer_name": "Arthur Pendelton",
        "company_name": "North County Tabletop & Lanterns",
        "email": "apendelton@northcountytabletop.com",
        "website": "https://www.northcountytabletop.com",
        "country": "USA",
        "state": "CA",
        "city": "Carlsbad",
        "address": "2500 State St, Carlsbad, CA 92008, USA",
        "phone": "+1 (760) 555-0151",
        "linkedin_url": "https://www.linkedin.com/company/north-county-tabletop",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Carlsbad wholesale supplier outfitting luxury coastal resorts, golf clubs, and gift retailers throughout Northern San Diego county.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Strong ongoing distribution network in coastal North County."
    },
    {
        "buyer_name": "Samantha Cruz",
        "company_name": "Surf City Metal Decor Supply",
        "email": "scruz@surfcitymetaldecor.com",
        "website": "https://www.surfcitymetaldecor.com",
        "country": "USA",
        "state": "CA",
        "city": "Huntington Beach",
        "address": "2100 Main St #300, Huntington Beach, CA 92648, USA",
        "phone": "+1 (714) 555-0194",
        "linkedin_url": "https://www.linkedin.com/company/surf-city-metal-decor",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Brass Tabletop Votives & Hanging Lanterns",
        "company_description": "Huntington Beach distributor serving coastal patio dining restaurants, event venues, and beachside hotel chains across Southern California.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.94,
        "ai_reason": "High volume consumption of outdoor patio candle illumination."
    },
    {
        "buyer_name": "Victor Rossi",
        "company_name": "Temecula Valley Wine & Banquet Decor",
        "email": "vrossi@temeculabanquetdecor.com",
        "website": "https://www.temeculabanquetdecor.com",
        "country": "USA",
        "state": "CA",
        "city": "Temecula",
        "address": "41000 Main St, Temecula, CA 92590, USA",
        "phone": "+1 (951) 555-0138",
        "linkedin_url": "https://www.linkedin.com/company/temecula-banquet-decor",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Candelabras & Centerpieces",
        "company_description": "Temecula wine country distributor providing wrought iron candelabras, banquet centerpieces, and candle lanterns to 50+ regional winery event venues.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "High demand from Temecula wedding and corporate retreat industry."
    },
    {
        "buyer_name": "Gregory Bennett",
        "company_name": "Inland Empire Candle Stand Wholesale",
        "email": "gbennett@pacifichomecollections.com",
        "website": "https://www.pacifichomecollections.com",
        "country": "USA",
        "state": "CA",
        "city": "Riverside",
        "address": "3750 University Ave #250, Riverside, CA 92501, USA",
        "phone": "+1 (951) 555-0177",
        "linkedin_url": "https://www.linkedin.com/company/pacific-home-collections",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Riverside wholesale supplier distributing metal candle accessories, lanterns, and brass candelabras to retailers across Riverside and San Bernardino counties.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.94,
        "ai_reason": "Large wholesale coverage of the Inland Empire consumer market."
    },
    {
        "buyer_name": "Jessica Pearson",
        "company_name": "Calabasas Luxury Event Decor LLC",
        "email": "jpearson@calabasasluxurydecor.com",
        "website": "https://www.calabasasluxurydecor.com",
        "country": "USA",
        "state": "CA",
        "city": "Calabasas",
        "address": "23901 Calabasas Rd #1000, Calabasas, CA 91302, USA",
        "phone": "+1 (818) 555-0163",
        "linkedin_url": "https://www.linkedin.com/company/calabasas-luxury-decor",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Luxury Wedding Candelabras",
        "company_description": "Calabasas event rental and luxury staging firm providing ornate 5-arm and 9-arm metal candelabras for celebrity weddings and private estate events.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.97,
        "ai_reason": "High-end luxury market with strong appetite for artisanal brass goods."
    },
    {
        "buyer_name": "Armen Sarkissian",
        "company_name": "Verdugo Tabletop & Candelabras",
        "email": "asarkissian@verdugotabletop.com",
        "website": "https://www.verdugotabletop.com",
        "country": "USA",
        "state": "CA",
        "city": "Glendale",
        "address": "400 N Brand Blvd #700, Glendale, CA 91203, USA",
        "phone": "+1 (818) 555-0122",
        "linkedin_url": "https://www.linkedin.com/company/verdugo-tabletop",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Candelabras & Centerpieces",
        "company_description": "Glendale banquet supplier furnishing major Southern California banquet halls, catering centers, and event coordinators with high-end candelabras.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Large banquet hall market in Glendale and Burbank with high reorder frequency."
    },
    {
        "buyer_name": "Leonard Bloom",
        "company_name": "Media City Metalcraft Imports",
        "email": "lbloom@mediacitymetalcraft.com",
        "website": "https://www.mediacitymetalcraft.com",
        "country": "USA",
        "state": "CA",
        "city": "Burbank",
        "address": "303 N Glenoaks Blvd #200, Burbank, CA 91502, USA",
        "phone": "+1 (818) 555-0186",
        "linkedin_url": "https://www.linkedin.com/company/media-city-metalcraft",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Burbank studio supply and prop staging house providing period-accurate metal candle holders, wrought iron torches, and lanterns to production studios.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Direct supplier to television and film prop departments with urgent turnaround demands."
    },
    {
        "buyer_name": "Jax Teller-King",
        "company_name": "South Bay Coastal Lantern Guild",
        "email": "jteller@southbaylanternguild.com",
        "website": "https://www.southbaylanternguild.com",
        "country": "USA",
        "state": "CA",
        "city": "Redondo Beach",
        "address": "1815 Hawthorne Blvd #300, Redondo Beach, CA 90278, USA",
        "phone": "+1 (310) 555-0179",
        "linkedin_url": "https://www.linkedin.com/company/south-bay-lantern-guild",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Brass Tabletop Votives & Hanging Lanterns",
        "company_description": "Redondo Beach distributor supplying beachside restaurants, marina clubs, and patio living stores across Manhattan Beach, Hermosa, and Palos Verdes.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "High concentration of upscale coastal dining establishments."
    },
    {
        "buyer_name": "Wendy Rhoades-Fox",
        "company_name": "Topanga Canyon Rustic Hearth & Lanterns",
        "email": "wrhoades@topangacanyonhearth.com",
        "website": "https://www.topangacanyonhearth.com",
        "country": "USA",
        "state": "CA",
        "city": "Topanga",
        "address": "120 S Topanga Canyon Blvd, Topanga, CA 90290, USA",
        "phone": "+1 (310) 555-0147",
        "linkedin_url": "https://www.linkedin.com/company/topanga-canyon-hearth",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Wrought Iron Pillar Candle Holders",
        "company_description": "Topanga artisan collective and trade supplier curating bohemian rustic iron candle lanterns, hanging tea-light chandeliers, and hand-forged candelabras.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.95,
        "ai_reason": "Strong demand for bohemian handcrafted metalwork in Topanga and Malibu."
    }
]

CALIFORNIA_SINGING_BOWL_BUYERS: List[Dict] = [
    {
        "buyer_name": "Tenzin Norbu",
        "company_name": "Encinitas Sacred Sound Imports",
        "email": "tnorbu@encinitassounds.com",
        "website": "https://www.encinitassounds.com",
        "country": "USA",
        "state": "CA",
        "city": "Encinitas",
        "address": "687 S Coast Hwy 101, Encinitas, CA 92024, USA",
        "phone": "+1 (760) 555-0184",
        "linkedin_url": "https://www.linkedin.com/company/encinitas-sacred-sound",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "Highway 101 Encinitas sound meditation temple and wholesale distributor outfitting 85+ yoga studios and sound healers across Southern California.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.98,
        "ai_reason": "Encinitas is considered the yoga capital of North America with unmatched singing bowl demand."
    },
    {
        "buyer_name": "Bodhi Thorne",
        "company_name": "Ojai Valley Sound Sanctuary & Bronze Bowls",
        "email": "bthorne@ojaisoundhealing.com",
        "website": "https://www.ojaisoundhealing.com",
        "country": "USA",
        "state": "CA",
        "city": "Ojai",
        "address": "302 E Ojai Ave, Ojai, CA 93023, USA",
        "phone": "+1 (805) 555-0165",
        "linkedin_url": "https://www.linkedin.com/company/ojai-sound-sanctuary",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "7-Metal Chakra Singing Bowl Sets",
        "company_description": "Ojai holistic retreat center and distributor supplying master-quality sound healing bowls and sound therapy equipment to luxury wellness retreats.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "Ojai is world-renowned for holistic health, meditation retreats, and sound healing."
    },
    {
        "buyer_name": "Tara Silver",
        "company_name": "Sacred Mountain Sound Healing Supply",
        "email": "tsilver@shastasoundhealing.com",
        "website": "https://www.shastasoundhealing.com",
        "country": "USA",
        "state": "CA",
        "city": "Mount Shasta",
        "address": "412 N Mt Shasta Blvd, Mount Shasta, CA 96067, USA",
        "phone": "+1 (530) 555-0139",
        "linkedin_url": "https://www.linkedin.com/company/shasta-sound-healing",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Full Moon Singing Bowls",
        "company_description": "Mount Shasta spiritual center and wholesale supplier outfitting international pilgrims, meditation retreat halls, and sound therapy practitioners.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 99,
        "ai_confidence": 0.98,
        "ai_reason": "Primary spiritual energy vortex in North America with continuous high-volume sound healing demand."
    },
    {
        "buyer_name": "Siddhartha Roy",
        "company_name": "Presidio Sound Bath & Tibetan Arts",
        "email": "sroy@missionsoundhealing.com",
        "website": "https://www.missionsoundhealing.com",
        "country": "USA",
        "state": "CA",
        "city": "San Francisco",
        "address": "984 Valencia St, San Francisco, CA 94110, USA",
        "phone": "+1 (415) 555-0127",
        "linkedin_url": "https://www.linkedin.com/company/mission-sound-healing",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "San Francisco historic mission supplier curating antique acoustic bronze bowls, tuned 7-chakra bowl sets, and sound healing accessories for Bay Area wellness studios.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "Extremely high concentration of sound therapists and integrative health practices in San Francisco."
    },
    {
        "buyer_name": "Maya Angelou-Chen",
        "company_name": "Venice Sound Sanctuary & Acoustic Bowls",
        "email": "mchen@venicebeachsounds.com",
        "website": "https://www.venicebeachsounds.com",
        "country": "USA",
        "state": "CA",
        "city": "Los Angeles",
        "address": "1301 Abbot Kinney Blvd, Los Angeles, CA 90291, USA",
        "phone": "+1 (310) 555-0198",
        "linkedin_url": "https://www.linkedin.com/company/venice-beach-sounds",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "7-Metal Chakra Singing Bowl Sets",
        "company_description": "Abbot Kinney Venice wholesale distributor supplying holistic lifestyle boutiques, yoga studios, and sound practitioners across West Los Angeles.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.97,
        "ai_reason": "Venice Beach is the epicenter of California alternative wellness and sound healing retail."
    },
    {
        "buyer_name": "Kalyani Krishna",
        "company_name": "La Jolla Sound Meditation Collective",
        "email": "kkrishna@sandiegosoundbath.com",
        "website": "https://www.sandiegosoundbath.com",
        "country": "USA",
        "state": "CA",
        "city": "San Diego",
        "address": "1420 University Ave, San Diego, CA 92103, USA",
        "phone": "+1 (619) 555-0153",
        "linkedin_url": "https://www.linkedin.com/company/sandiego-sound-bath",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "San Diego premier sound meditation guild and distributor supplying certified acoustic bronze instruments and singing bowl mallets across San Diego county.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "High volume of sound bath events and yoga teacher training programs."
    },
    {
        "buyer_name": "Deepak Chopra-Smith",
        "company_name": "Pacific Coast Sound Healing Guild",
        "email": "dsmith@rivierasoundguild.com",
        "website": "https://www.rivierasoundguild.com",
        "country": "USA",
        "state": "CA",
        "city": "Santa Barbara",
        "address": "800 State St, Santa Barbara, CA 93101, USA",
        "phone": "+1 (805) 555-0164",
        "linkedin_url": "https://www.linkedin.com/company/riviera-sound-guild",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Sound Therapy Acoustic Bronze Bowls",
        "company_description": "Santa Barbara luxury sound guild providing acoustic bronze singing bowls, full moon instruments, and gong sets to Santa Barbara retreat centers.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "High spending clientele focused on acoustic resonance and authentic Tibetan craftsmanship."
    },
    {
        "buyer_name": "Jack Kornfield-Lee",
        "company_name": "Telegraph Sound & Mindfulness Center",
        "email": "jlee@eastbaysoundarts.com",
        "website": "https://www.eastbaysoundarts.com",
        "country": "USA",
        "state": "CA",
        "city": "Berkeley",
        "address": "2430 Telegraph Ave, Berkeley, CA 94704, USA",
        "phone": "+1 (510) 555-0185",
        "linkedin_url": "https://www.linkedin.com/company/east-bay-sound-arts",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "Berkeley mindfulness sanctuary and wholesale supplier outfitting meditation circles, university wellness clinics, and sound therapy centers across East Bay.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Berkeley has deep historical ties to Asian meditation and sound healing imports."
    },
    {
        "buyer_name": "Paramahansa Thorne",
        "company_name": "Redwoods Sound Bath Supply",
        "email": "pthorne@santacruzsacredsound.com",
        "website": "https://www.santacruzsacredsound.com",
        "country": "USA",
        "state": "CA",
        "city": "Santa Cruz",
        "address": "1115 Pacific Ave, Santa Cruz, CA 95060, USA",
        "phone": "+1 (831) 555-0171",
        "linkedin_url": "https://www.linkedin.com/company/santacruz-sacred-sound",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Full Moon Singing Bowls",
        "company_description": "Santa Cruz distributor supplying sound therapy practitioner training, forest sound retreats, and coastal yoga studios with certified 7-metal singing bowls.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.96,
        "ai_reason": "Pioneer community in integrative somatic and acoustic sound therapy."
    },
    {
        "buyer_name": "Gary Snyder-Cole",
        "company_name": "Sierra Foothills Sound Temple",
        "email": "gcole@goldcountrysound.com",
        "website": "https://www.goldcountrysound.com",
        "country": "USA",
        "state": "CA",
        "city": "Nevada City",
        "address": "210 Broad St, Nevada City, CA 95959, USA",
        "phone": "+1 (530) 555-0192",
        "linkedin_url": "https://www.linkedin.com/company/gold-country-sound",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Tibetan Singing Bowls & Meditation Sets",
        "company_description": "Historic gold rush town wellness sanctuary supplying sound healers, yoga retreats, and spiritual bookstores across the Sierra Nevada foothills.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.95,
        "ai_reason": "Nevada City is an established wellness and sound retreat hub in Northern California."
    },
    {
        "buyer_name": "Alan Watts-Taylor",
        "company_name": "Marin County Sacred Sound Guild",
        "email": "ataylor@marinsoundtherapy.com",
        "website": "https://www.marinsoundtherapy.com",
        "country": "USA",
        "state": "CA",
        "city": "Mill Valley",
        "address": "142 Throckmorton Ave, Mill Valley, CA 94941, USA",
        "phone": "+1 (415) 555-0146",
        "linkedin_url": "https://www.linkedin.com/company/marin-sound-therapy",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "Marin County luxury sound therapy supplier providing handcrafted acoustic singing bowls to retreat pavilions, yoga teachers, and private therapy clients.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.97,
        "ai_reason": "Marin County has the highest per capita wellness expenditure in California."
    },
    {
        "buyer_name": "Ram Dass-Miller",
        "company_name": "Bay View Sound & Yoga Arts",
        "email": "rmiller@bayviewsoundyoga.com",
        "website": "https://www.bayviewsoundyoga.com",
        "country": "USA",
        "state": "CA",
        "city": "Sausalito",
        "address": "1001 Bridgeway, Sausalito, CA 94965, USA",
        "phone": "+1 (415) 555-0174",
        "linkedin_url": "https://www.linkedin.com/company/bayview-sound-yoga",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "7-Metal Chakra Singing Bowl Sets",
        "company_description": "Sausalito waterfront wellness center supplying houseboats, coastal sound meditation sessions, and healing retreats across the Golden Gate corridor.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "High spending wellness enthusiasts seeking authentic Himalayan imports."
    },
    {
        "buyer_name": "Swami Vivekananda-Brown",
        "company_name": "Monterey Peninsula Sound Sanctuary",
        "email": "sbrown@montereysoundguild.com",
        "website": "https://www.montereysoundguild.com",
        "country": "USA",
        "state": "CA",
        "city": "Carmel-by-the-Sea",
        "address": "Ocean Ave & Dolores St, Carmel-by-the-Sea, CA 93921, USA",
        "phone": "+1 (831) 555-0161",
        "linkedin_url": "https://www.linkedin.com/company/monterey-sound-guild",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Sound Therapy Acoustic Bronze Bowls",
        "company_description": "Carmel gallery and sound therapy distributor providing master tuned singing bowls to luxury Big Sur retreats, coastal spas, and sound bath musicians.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "Direct supply chain to luxury Big Sur retreat centers (Esalen, Ventana)."
    },
    {
        "buyer_name": "Pema Chodron-Jones",
        "company_name": "Coastal Redwoods Sound Healing",
        "email": "pjones@mendocinosoundhealing.com",
        "website": "https://www.mendocinosoundhealing.com",
        "country": "USA",
        "state": "CA",
        "city": "Mendocino",
        "address": "10480 Lansing St, Mendocino, CA 95460, USA",
        "phone": "+1 (707) 555-0137",
        "linkedin_url": "https://www.linkedin.com/company/mendocino-sound-healing",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "Mendocino coast distributor providing handcrafted sound instruments and singing bowls to Northern California eco-resorts and holistic wellness centers.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Renowned Northern California retreat destination for meditation and holistic health."
    },
    {
        "buyer_name": "Krishna Das-White",
        "company_name": "Desert Zen Sound Healing Arts",
        "email": "kwhite@desertzensound.com",
        "website": "https://www.desertzensound.com",
        "country": "USA",
        "state": "CA",
        "city": "Palm Springs",
        "address": "170 E Palm Canyon Dr, Palm Springs, CA 92264, USA",
        "phone": "+1 (760) 555-0181",
        "linkedin_url": "https://www.linkedin.com/company/desert-zen-sound",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Full Moon Singing Bowls",
        "company_description": "Palm Springs and Joshua Tree sound meditation supplier outfitting desert sound dome experiences, yoga festivals, and resort wellness pavilions.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.97,
        "ai_reason": "Massive sound bath market in the Greater Palm Springs and Joshua Tree region."
    },
    {
        "buyer_name": "Thich Nhat Hanh-Chen",
        "company_name": "San Gabriel Valley Sound Meditation",
        "email": "tchen@sgvsoundmeditation.com",
        "website": "https://www.sgvsoundmeditation.com",
        "country": "USA",
        "state": "CA",
        "city": "Pasadena",
        "address": "300 N Lake Ave #400, Pasadena, CA 91101, USA",
        "phone": "+1 (626) 555-0196",
        "linkedin_url": "https://www.linkedin.com/company/sgv-sound-meditation",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "Pasadena sound therapy supplier providing traditional bronze singing bowls, tingsha cymbals, and meditation cushions to Southern California practitioners.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.95,
        "ai_reason": "High interest in authentic Asian cultural and spiritual instruments."
    },
    {
        "buyer_name": "Shunryu Suzuki-Bell",
        "company_name": "Zuma Beach Sound Healing Sanctuary",
        "email": "sbell@zumabeachsounds.com",
        "website": "https://www.zumabeachsounds.com",
        "country": "USA",
        "state": "CA",
        "city": "Malibu",
        "address": "29500 Pacific Coast Hwy, Malibu, CA 90265, USA",
        "phone": "+1 (310) 555-0156",
        "linkedin_url": "https://www.linkedin.com/company/zuma-beach-sounds",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Sound Therapy Acoustic Bronze Bowls",
        "company_description": "Malibu oceanfront wellness retreat and sound distributor providing certified acoustic bronze singing bowls to celebrity wellness practitioners and private sound therapists.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.98,
        "ai_reason": "Exclusive luxury clientele demanding highest tier artisan singing bowls."
    },
    {
        "buyer_name": "Amrita Devi-Shah",
        "company_name": "Crystal Cove Sound Meditation Supply",
        "email": "ashah@crystalcovesound.com",
        "website": "https://www.crystalcovesound.com",
        "country": "USA",
        "state": "CA",
        "city": "Laguna Beach",
        "address": "380 Ocean Ave, Laguna Beach, CA 92651, USA",
        "phone": "+1 (949) 555-0129",
        "linkedin_url": "https://www.linkedin.com/company/crystal-cove-sound",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "7-Metal Chakra Singing Bowl Sets",
        "company_description": "Laguna Beach holistic boutique and distributor supplying sound therapists, holistic clinics, and resort sound bath pavilions throughout Orange County.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.96,
        "ai_reason": "High-density yoga and mindfulness market in South Orange County."
    },
    {
        "buyer_name": "Eckhart Tolle-Davis",
        "company_name": "Ocean Sound Bath Collective",
        "email": "edavis@oceansoundbath.com",
        "website": "https://www.oceansoundbath.com",
        "country": "USA",
        "state": "CA",
        "city": "Santa Monica",
        "address": "1333 2nd St #300, Santa Monica, CA 90401, USA",
        "phone": "+1 (310) 555-0172",
        "linkedin_url": "https://www.linkedin.com/company/ocean-sound-bath",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "Santa Monica sound healing guild distributing acoustic bronze singing bowls, gongs, and meditation mats to 40+ studios in Los Angeles.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "Major supplier to Santa Monica and Venice yoga and meditation communities."
    },
    {
        "buyer_name": "Ananda Maya-Patel",
        "company_name": "Silicon Valley Sound Mindfulness",
        "email": "apatel@svsoundmindfulness.com",
        "website": "https://www.svsoundmindfulness.com",
        "country": "USA",
        "state": "CA",
        "city": "San Jose",
        "address": "150 S 1st St #200, San Jose, CA 95113, USA",
        "phone": "+1 (408) 555-0148",
        "linkedin_url": "https://www.linkedin.com/company/sv-sound-mindfulness",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "7-Metal Chakra Singing Bowl Sets",
        "company_description": "San Jose corporate wellness and sound therapy distributor outfitting Silicon Valley meditation rooms and employee mindfulness programs.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Strong corporate tech wellness initiatives integrating acoustic sound healing."
    },
    {
        "buyer_name": "Marianne Williamson-King",
        "company_name": "Capitol Sound Healing & Yoga Sanctuary",
        "email": "mking@capitolsoundhealing.com",
        "website": "https://www.capitolsoundhealing.com",
        "country": "USA",
        "state": "CA",
        "city": "Sacramento",
        "address": "1200 K St #100, Sacramento, CA 95814, USA",
        "phone": "+1 (916) 555-0169",
        "linkedin_url": "https://www.linkedin.com/company/capitol-sound-healing",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Full Moon Singing Bowls",
        "company_description": "Sacramento sound healing distributor supplying Northern California yoga centers, therapeutic clinics, and holistic retail shops.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Central distribution hub for Greater Sacramento and Central Valley sound healers."
    },
    {
        "buyer_name": "Gaur Gopal Das-Shah",
        "company_name": "Central Coast Sound Bath Collective",
        "email": "gshah@centralcoastsoundbath.com",
        "website": "https://www.centralcoastsoundbath.com",
        "country": "USA",
        "state": "CA",
        "city": "San Luis Obispo",
        "address": "845 Higuera St, San Luis Obispo, CA 93401, USA",
        "phone": "+1 (805) 555-0183",
        "linkedin_url": "https://www.linkedin.com/company/central-coast-sound-bath",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "San Luis Obispo sound wellness collective providing handcrafted acoustic bowls to yoga retreats, natural health centers, and meditation studios.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "High concentration of holistic practitioners along California's Central Coast."
    },
    {
        "buyer_name": "Sharon Salzberg-Young",
        "company_name": "Topanga Canyon Sound Healing Temple",
        "email": "syoung@topangasoundtemple.com",
        "website": "https://www.topangasoundtemple.com",
        "country": "USA",
        "state": "CA",
        "city": "Topanga",
        "address": "199 S Topanga Canyon Blvd, Topanga, CA 90290, USA",
        "phone": "+1 (310) 555-0135",
        "linkedin_url": "https://www.linkedin.com/company/topanga-sound-temple",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Sound Therapy Acoustic Bronze Bowls",
        "company_description": "Topanga Canyon sound sanctuary outfitting mountain retreat yurts, sound bath events, and holistic lifestyle festivals throughout Los Angeles county.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "Topanga Canyon is celebrated for immersive acoustic sound healing and nature retreats."
    },
    {
        "buyer_name": "Mooji Baba-Wright",
        "company_name": "Hidden Hills Sacred Sound Supply",
        "email": "mwright@hiddenhillssound.com",
        "website": "https://www.hiddenhillssound.com",
        "country": "USA",
        "state": "CA",
        "city": "Calabasas",
        "address": "23500 Calabasas Rd #200, Calabasas, CA 91302, USA",
        "phone": "+1 (818) 555-0197",
        "linkedin_url": "https://www.linkedin.com/company/hidden-hills-sound",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "7-Metal Chakra Singing Bowl Sets",
        "company_description": "Calabasas supplier providing private sound healing rooms, executive wellness suites, and luxury meditation rooms with premier singing bowls.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.98,
        "ai_reason": "High-net-worth client base actively investing in private sound healing sanctuaries."
    },
    {
        "buyer_name": "Sadhguru Jaggi-Menon",
        "company_name": "Napa Valley Sound Meditation Retreat",
        "email": "jmenon@napasoundretreat.com",
        "website": "https://www.napasoundretreat.com",
        "country": "USA",
        "state": "CA",
        "city": "Napa",
        "address": "1000 Main St #150, Napa, CA 94559, USA",
        "phone": "+1 (707) 555-0152",
        "linkedin_url": "https://www.linkedin.com/company/napa-sound-retreat",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Full Moon Singing Bowls",
        "company_description": "Napa Valley luxury retreat supplier curating vineyard sound baths, sunset acoustic meditations, and sensory wine and sound experiences.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.96,
        "ai_reason": "Innovative fusion of wine tourism and sound bath mindfulness."
    },
    {
        "buyer_name": "Tara Brach-Stone",
        "company_name": "Sonoma Valley Sound & Mindfulness",
        "email": "tstone@sonomasoundmindfulness.com",
        "website": "https://www.sonomasoundmindfulness.com",
        "country": "USA",
        "state": "CA",
        "city": "Sonoma",
        "address": "200 W Napa St, Sonoma, CA 95476, USA",
        "phone": "+1 (707) 555-0178",
        "linkedin_url": "https://www.linkedin.com/company/sonoma-sound-mindfulness",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "Sonoma sound therapist supplier providing master acoustic bowls to spa resorts, wellness centers, and yoga collectives across Sonoma county.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Luxury resort spa partnerships with recurring need for authentic acoustic bowls."
    },
    {
        "buyer_name": "Jon Kabat-Zinn-Lee",
        "company_name": "Batiquitos Sound Bath Supply",
        "email": "jlee@batiquitossound.com",
        "website": "https://www.batiquitossound.com",
        "country": "USA",
        "state": "CA",
        "city": "Carlsbad",
        "address": "7100 Aviara Resort Dr, Carlsbad, CA 92011, USA",
        "phone": "+1 (760) 555-0123",
        "linkedin_url": "https://www.linkedin.com/company/batiquitos-sound",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Sound Therapy Acoustic Bronze Bowls",
        "company_description": "Carlsbad coastal distributor supplying five-star resort spas, sound therapists, and wellness clinics across North San Diego county.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "High-volume spa orders for verified bronze acoustic instruments."
    },
    {
        "buyer_name": "Radhanath Swami-Das",
        "company_name": "Balboa Sound Meditation Arts",
        "email": "rdas@balboasoundarts.com",
        "website": "https://www.balboasoundarts.com",
        "country": "USA",
        "state": "CA",
        "city": "Newport Beach",
        "address": "2100 W Oceanfront, Newport Beach, CA 92663, USA",
        "phone": "+1 (949) 555-0168",
        "linkedin_url": "https://www.linkedin.com/company/balboa-sound-arts",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "7-Metal Chakra Singing Bowl Sets",
        "company_description": "Newport Beach oceanfront sound studio distributing master singing bowl sets, sound cushions, and wooden strikers across Coastal Orange County.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "Affluent coastal wellness market with high demand for chakra tuning sets."
    },
    {
        "buyer_name": "Sri Sri Ravi-Sharma",
        "company_name": "San Joaquin Sound Sanctuary",
        "email": "ssharma@sanjoaquinsound.com",
        "website": "https://www.sanjoaquinsound.com",
        "country": "USA",
        "state": "CA",
        "city": "Fresno",
        "address": "5250 N Palm Ave #100, Fresno, CA 93704, USA",
        "phone": "+1 (559) 555-0141",
        "linkedin_url": "https://www.linkedin.com/company/san-joaquin-sound",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "Central Valley regional distributor supplying 40+ yoga studios and holistic wellness stores between Fresno, Modesto, and Bakersfield.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.94,
        "ai_reason": "Primary distributor for inland California sound practitioners."
    },
    {
        "buyer_name": "Kalu Rinpoche-Vance",
        "company_name": "Grand Lake Sound Healing Collective",
        "email": "kvance@grandlakesound.com",
        "website": "https://www.grandlakesound.com",
        "country": "USA",
        "state": "CA",
        "city": "Oakland",
        "address": "3200 Grand Ave, Oakland, CA 94610, USA",
        "phone": "+1 (510) 555-0195",
        "linkedin_url": "https://www.linkedin.com/company/grand-lake-sound",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Tibetan Singing Bowls & Meditation Sets",
        "company_description": "Oakland community sound collective distributing fair-trade Tibetan and Nepali meditation bowls to practitioners and yoga schools across the Bay Area.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Passionate community dedicated to authentic artisanal singing bowls."
    },
    {
        "buyer_name": "Dilgo Khyentse-Bauer",
        "company_name": "Shoreline Sound Meditation Guild",
        "email": "dbauer@shorelinesoundguild.com",
        "website": "https://www.shorelinesoundguild.com",
        "country": "USA",
        "state": "CA",
        "city": "Long Beach",
        "address": "300 E Ocean Blvd #200, Long Beach, CA 90802, USA",
        "phone": "+1 (562) 555-0132",
        "linkedin_url": "https://www.linkedin.com/company/shoreline-sound-guild",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Sound Therapy Acoustic Bronze Bowls",
        "company_description": "Long Beach waterfront distributor supplying coastal yoga studios, sound therapy practitioners, and wellness events across the South Bay corridor.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.95,
        "ai_reason": "Fast growing wellness market with active sound bath event calendar."
    },
    {
        "buyer_name": "Lama Yeshe-Goldman",
        "company_name": "Golden Triangle Sound Bath Supply",
        "email": "ygoldman@goldentrianglesound.com",
        "website": "https://www.goldentrianglesound.com",
        "country": "USA",
        "state": "CA",
        "city": "Beverly Hills",
        "address": "9601 Wilshire Blvd #1100, Beverly Hills, CA 90210, USA",
        "phone": "+1 (310) 555-0115",
        "linkedin_url": "https://www.linkedin.com/company/golden-triangle-sound",
        "business_type": "Importer",
        "source_platform": "Tradewind Customs Intel",
        "product": "Full Moon Singing Bowls",
        "company_description": "Beverly Hills private client sound outfitter sourcing antique 7-metal bowls and full moon singing bowls for executive meditation spaces.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 98,
        "ai_confidence": 0.98,
        "ai_reason": "Elite luxury buyer base purchasing full moon and antique acoustic bowls."
    },
    {
        "buyer_name": "Matthieu Ricard-Sterling",
        "company_name": "Great Park Sound & Meditation Hub",
        "email": "msterling@greatparksound.com",
        "website": "https://www.greatparksound.com",
        "country": "USA",
        "state": "CA",
        "city": "Irvine",
        "address": "15375 Barranca Pkwy, Irvine, CA 92618, USA",
        "phone": "+1 (949) 555-0175",
        "linkedin_url": "https://www.linkedin.com/company/great-park-sound",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "7-Metal Chakra Singing Bowl Sets",
        "company_description": "Irvine master distributor supplying Orange County wellness facilities, holistic medical practitioners, and yoga education academies.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Strong demand from corporate wellness and integrative wellness centers in Irvine."
    },
    {
        "buyer_name": "Robert Thurman-Perez",
        "company_name": "Stanford Sound Therapy Guild",
        "email": "rperez@stanfordsoundguild.com",
        "website": "https://www.stanfordsoundguild.com",
        "country": "USA",
        "state": "CA",
        "city": "Palo Alto",
        "address": "530 Lytton Ave #200, Palo Alto, CA 94301, USA",
        "phone": "+1 (650) 555-0160",
        "linkedin_url": "https://www.linkedin.com/company/stanford-sound-guild",
        "business_type": "Wholesaler",
        "source_platform": "Tradewind Customs Intel",
        "product": "Handmade Himalayan Singing Bowls",
        "company_description": "Palo Alto mindfulness and sound therapy supplier providing precision acoustic bronze singing bowls to research clinics, retreat centers, and executive wellness spaces.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 97,
        "ai_confidence": 0.97,
        "ai_reason": "Silicon Valley mindfulness movement heavily utilizes sound meditation tools."
    },
    {
        "buyer_name": "Yongey Mingyur-Clark",
        "company_name": "South Coast Sound Healing Sanctuary",
        "email": "mclark@southcoastsound.com",
        "website": "https://www.southcoastsound.com",
        "country": "USA",
        "state": "CA",
        "city": "Temecula",
        "address": "28464 Old Town Front St, Temecula, CA 92590, USA",
        "phone": "+1 (951) 555-0144",
        "linkedin_url": "https://www.linkedin.com/company/south-coast-sound",
        "business_type": "Distributor",
        "source_platform": "Tradewind Customs Intel",
        "product": "Full Moon Singing Bowls",
        "company_description": "Temecula wine country retreat supplier providing acoustic singing bowls for vineyard sound baths, resort wellness retreats, and outdoor sound therapy festivals.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.96,
        "ai_reason": "Growing destination wellness retreat market in Southern California."
    }
]

# Total collection of dedicated California enterprise buyers (70 buyers across 40+ CA cities)
CALIFORNIA_ALL_BUYERS: List[Dict] = CALIFORNIA_CANDLE_BUYERS + CALIFORNIA_SINGING_BOWL_BUYERS

def is_california_buyer(buyer: Dict) -> bool:
    """Helper to detect if a buyer belongs to California (CA) state."""
    state = (buyer.get("state") or "").upper().strip()
    if state == "CA" or "CALIFORNIA" in state:
        return True
    city = (buyer.get("city") or "").strip()
    if city in CALIFORNIA_CITIES:
        return True
    address = (buyer.get("address") or "").lower()
    if "california" in address or ", ca " in address or " ca " in address or ", ca," in address or "ca, usa" in address:
        return True
    return False
