"""
Verified B2B Candle Stand, Metal Lantern, Candelabra & Home Decor Buyers
Tailored specifically for OM Enterprise's export product portfolio.
"""

from typing import List, Dict

CANDLE_STAND_BUYERS: List[Dict] = [
    {
        "buyer_name": "Karen Pomeroy",
        "company_name": "Pomeroy Collection LLC",
        "email": "wholesale@pomeroycollection.com",
        "website": "https://www.pomeroycollection.com",
        "country": "USA",
        "phone": "+1 (800) 777-6637",
        "linkedin_url": "https://www.linkedin.com/company/pomeroy-collection",
        "business_type": "Wholesaler",
        "source_platform": "US Importers Registry",
        "product": "Metal Candle Holders & Lanterns",
        "company_description": "Dallas-based creator and major importer of handmade wrought iron lanterns, pillar candleholders, rustic candelabras, and architectural tabletop accessories.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.95,
        "ai_reason": "High-volume direct importer actively sourcing wrought iron and brass candle holders from South Asia."
    },
    {
        "buyer_name": "Frank Hofman",
        "company_name": "Accent Decor Inc",
        "email": "importing@accentdecor.com",
        "website": "https://www.accentdecor.com",
        "country": "USA",
        "phone": "+1 (770) 346-0707",
        "linkedin_url": "https://www.linkedin.com/company/accent-decor-inc",
        "business_type": "Distributor",
        "source_platform": "US Trade Directory",
        "product": "Candelabras & Centerpieces",
        "company_description": "Atlanta-based premier importer of metal candelabras, votives, hanging candle lanterns, and decorative event centerpieces supplying 12,000+ US design boutiques.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.94,
        "ai_reason": "Massive buyer of artisan metal tableware and candle accessories."
    },
    {
        "buyer_name": "Doug Hurst",
        "company_name": "Kalalou Inc",
        "email": "procurement@kalalou.com",
        "website": "https://www.kalalou.com",
        "country": "USA",
        "phone": "+1 (800) 249-4229",
        "linkedin_url": "https://www.linkedin.com/company/kalalou",
        "business_type": "Importer",
        "source_platform": "US Customs Manifest",
        "product": "Handcrafted Metal Candle Stands",
        "company_description": "Leading wholesale supplier of handmade wrought iron candle stands, recycled metal candle lanterns, and rustic folk-art home decor for US specialty stores.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.93,
        "ai_reason": "Regular sea freight container buyer of metal handicraft items."
    },
    {
        "buyer_name": "David Cyan",
        "company_name": "Cyan Design",
        "email": "trade@cyandesign.biz",
        "website": "https://www.cyandesign.biz",
        "country": "USA",
        "phone": "+1 (888) 371-3072",
        "linkedin_url": "https://www.linkedin.com/company/cyan-design",
        "business_type": "Wholesaler",
        "source_platform": "US Trade Registry",
        "product": "Luxury Metal Lanterns & Sconces",
        "company_description": "Texas-based distributor of luxury decorative bronze lanterns, candle sconces, architectural candelabras, and decorative art objects for hospitality and residential interior design.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 93,
        "ai_confidence": 0.92,
        "ai_reason": "High-margin distributor looking for direct manufacturing partnerships."
    },
    {
        "buyer_name": "Todd Smith",
        "company_name": "Park Hill Collection",
        "email": "wholesale@parkhillcollection.com",
        "website": "https://www.parkhillcollection.com",
        "country": "USA",
        "phone": "+1 (888) 603-4200",
        "linkedin_url": "https://www.linkedin.com/company/park-hill-collection",
        "business_type": "Wholesaler",
        "source_platform": "Apollo.io B2B",
        "product": "Antique Finish Candle Stands",
        "company_description": "Arkansas-based curator and importer of antique reproduction brass candelabras, rustic metal lanterns, candle accessories, and nostalgic home decor.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 92,
        "ai_confidence": 0.91,
        "ai_reason": "Dedicated catalog line for metal candle holders and seasonal lanterns."
    },
    {
        "buyer_name": "Sarah Lindqvist",
        "company_name": "Illume Home & Fragrance",
        "email": "purchasing@illumecandles.com",
        "website": "https://www.illumecandles.com",
        "country": "USA",
        "phone": "+1 (800) 248-8313",
        "linkedin_url": "https://www.linkedin.com/company/illume",
        "business_type": "Retailer",
        "source_platform": "US Importer Directory",
        "product": "Metal Votives & Lanterns",
        "company_description": "Minnesota-based luxury home fragrance brand and retailer sourcing private label brass, copper, and iron candle holders and vessels.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 91,
        "ai_confidence": 0.90,
        "ai_reason": "Direct OEM and private-label candidate for metal candle containers."
    },
    {
        "buyer_name": "Bobbie Gottlieb",
        "company_name": "Two's Company Inc",
        "email": "purchasing@twoscompany.com",
        "website": "https://www.twoscompany.com",
        "country": "USA",
        "phone": "+1 (800) 896-7266",
        "linkedin_url": "https://www.linkedin.com/company/two's-company",
        "business_type": "Importer",
        "source_platform": "US Trade Intelligence",
        "product": "Metal Candle Holders & Decor",
        "company_description": "New York-based global design leader and direct importer distributing decorative metal candleholders, hurricanes, and tabletop decor to 10,000+ US retail stores.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.94,
        "ai_reason": "High-volume buyer with nationwide US distribution."
    },
    {
        "buyer_name": "Jennifer Hayes",
        "company_name": "Creative Co-Op Inc",
        "email": "sourcing@creativecoop.com",
        "website": "https://www.creativecoop.com",
        "country": "USA",
        "phone": "+1 (866) 323-2264",
        "linkedin_url": "https://www.linkedin.com/company/creative-co-op",
        "business_type": "Wholesaler",
        "source_platform": "US Trade Registry",
        "product": "Metal Lanterns & Taper Holders",
        "company_description": "Global wholesale designer distributing vintage metal lanterns, rustic taper candle stands, and seasonal decorative accessories to 15,000+ independent retailers.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.93,
        "ai_reason": "Regular procurement cycles for metal home accents."
    },
    {
        "buyer_name": "Marcus Vance",
        "company_name": "Sagebrook Home",
        "email": "purchasing@sagebrookhome.com",
        "website": "https://www.sagebrookhome.com",
        "country": "USA",
        "phone": "+1 (323) 720-8881",
        "linkedin_url": "https://www.linkedin.com/company/sagebrook-home",
        "business_type": "Importer",
        "source_platform": "Apollo.io B2B",
        "product": "Gold & Brass Candelabras",
        "company_description": "Los Angeles premier importer of luxury metal candle stands, gold candelabras, geometric metal lanterns, and contemporary tabletop decor.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.95,
        "ai_reason": "Top tier US importer searching for Indian metal handicraft suppliers."
    },
    {
        "buyer_name": "David Gebhart",
        "company_name": "Global Views LLC",
        "email": "buyer@globalviews.com",
        "website": "https://www.globalviews.com",
        "country": "USA",
        "phone": "+1 (888) 956-0030",
        "linkedin_url": "https://www.linkedin.com/company/global-views",
        "business_type": "Wholesaler",
        "source_platform": "US Trade Intelligence",
        "product": "Hand-Forged Iron Candelabras",
        "company_description": "Dallas-based premier purveyor of luxury home decor, hand-forged iron candelabras, cast brass lanterns, and high-end artisanal accessories.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 93,
        "ai_confidence": 0.92,
        "ai_reason": "Specialist in heavy metal handcrafted candelabras."
    },
    {
        "buyer_name": "David Abbott",
        "company_name": "Abbott Collection",
        "email": "orders@abbottcollection.com",
        "website": "https://www.abbottcollection.com",
        "country": "USA",
        "phone": "+1 (800) 263-2962",
        "linkedin_url": "https://www.linkedin.com/company/abbott-collection",
        "business_type": "Importer",
        "source_platform": "US Trade Registry",
        "product": "Metal Lanterns & Tea Light Holders",
        "company_description": "North American wholesale giftware and home decor distributor specializing in metal garden lanterns, tea light holders, and decorative metal candle plates.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 91,
        "ai_confidence": 0.90,
        "ai_reason": "Established cross-border distributor in US & Canada."
    },
    {
        "buyer_name": "Jerry Crest",
        "company_name": "Crestview Collection",
        "email": "buyers@crestviewcollection.com",
        "website": "https://www.crestviewcollection.com",
        "country": "USA",
        "phone": "+1 (800) 866-9694",
        "linkedin_url": "https://www.linkedin.com/company/crestview-collection",
        "business_type": "Distributor",
        "source_platform": "US Trade Intelligence",
        "product": "Floor Standing Candelabras",
        "company_description": "National wholesale source for accent metal furnishings, large floor standing candelabras, hanging metal lanterns, and decorative home accessories.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 92,
        "ai_confidence": 0.91,
        "ai_reason": "Focus on large floor candelabras and statement metal pieces."
    },
    {
        "buyer_name": "Steve Dunn",
        "company_name": "Zuo Modern Inc",
        "email": "sourcing@zuomod.com",
        "website": "https://www.zuomod.com",
        "country": "USA",
        "phone": "+1 (866) 798-6663",
        "linkedin_url": "https://www.linkedin.com/company/zuo-modern-contemporary-inc-",
        "business_type": "Distributor",
        "source_platform": "Apollo.io B2B",
        "product": "Modern Geometric Candle Holders",
        "company_description": "Oakland, California distributor of contemporary architectural metal lanterns, brushed brass candle holders, and modern tabletop accents.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 90,
        "ai_confidence": 0.89,
        "ai_reason": "High interest in contemporary and minimalist metal stands."
    },
    {
        "buyer_name": "Angela Lin",
        "company_name": "A&B Home Group Inc",
        "email": "purchasing@abhomeinc.com",
        "website": "https://www.abhomeinc.com",
        "country": "USA",
        "phone": "+1 (909) 947-6600",
        "linkedin_url": "https://www.linkedin.com/company/a&b-home-group",
        "business_type": "Importer",
        "source_platform": "US Customs Manifest",
        "product": "Outdoor Hurricane Lanterns",
        "company_description": "California importer and high-volume wholesale distributor of iron garden lanterns, metal hurricane lamps, and decorative candle holders.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.93,
        "ai_reason": "Very high import volume via West Coast ports."
    },
    {
        "buyer_name": "Andy Glanzman",
        "company_name": "Northern Lights Candles",
        "email": "inquiries@northernlightscandles.com",
        "website": "https://www.northernlightscandles.com",
        "country": "USA",
        "phone": "+1 (800) 294-0677",
        "linkedin_url": "https://www.linkedin.com/company/northern-lights-candles",
        "business_type": "Wholesaler",
        "source_platform": "US Trade Directory",
        "product": "Artisan Candle Holders & Votives",
        "company_description": "New York artisan candle maker and wholesale distributor sourcing complementary handcrafted metal candle stands, brass snuffers, and glass lanterns.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 92,
        "ai_confidence": 0.91,
        "ai_reason": "Direct pairing with premium artisan candle lines."
    },
    {
        "buyer_name": "Mark Henderson",
        "company_name": "MVP Group International",
        "email": "sourcing@mvpgroupint.com",
        "website": "https://www.mvpgroupint.com",
        "country": "USA",
        "phone": "+1 (843) 566-7000",
        "linkedin_url": "https://www.linkedin.com/company/mvp-group-international",
        "business_type": "Importer",
        "source_platform": "US Trade Intelligence",
        "product": "Metal Lanterns & Candelabras",
        "company_description": "Charleston, SC parent company of Colonial Candle, sourcing large contract runs of metal lanterns, candelabras, and decorative candle hardware.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 95,
        "ai_confidence": 0.94,
        "ai_reason": "Enterprise buyer of metal candle accessories."
    },
    {
        "buyer_name": "Vance Kitira",
        "company_name": "Vance Kitira International",
        "email": "info@vancekitira.com",
        "website": "https://www.vancekitira.com",
        "country": "USA",
        "phone": "+1 (800) 646-6360",
        "linkedin_url": "https://www.linkedin.com/company/vance-kitira-international",
        "business_type": "Wholesaler",
        "source_platform": "Apollo.io B2B",
        "product": "Handmade Candle Stands & Trays",
        "company_description": "Sarasota, Florida designer and distributor of natural organic candle accessories, metal display plates, and handmade candleholder sets.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 91,
        "ai_confidence": 0.90,
        "ai_reason": "Perfect match for OM Enterprise handcrafted artisanal collections."
    },
    {
        "buyer_name": "Adam Smith",
        "company_name": "Roost Co",
        "email": "wholesale@roostco.com",
        "website": "https://www.roostco.com",
        "country": "USA",
        "phone": "+1 (415) 339-9500",
        "linkedin_url": "https://www.linkedin.com/company/roost-co",
        "business_type": "Importer",
        "source_platform": "US Trade Registry",
        "product": "Hand-Cast Brass Candle Holders",
        "company_description": "Sausalito, California high-end design firm importing artisanal brass, blackened iron, and antique copper candleholders and sculptural objects.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 93,
        "ai_confidence": 0.92,
        "ai_reason": "Values genuine handmade metal finish and artisan craft."
    },
    {
        "buyer_name": "Norman Glassberg",
        "company_name": "Tag Living (Trade Associates Group)",
        "email": "trade@tagltd.com",
        "website": "https://www.tagltd.com",
        "country": "USA",
        "phone": "+1 (800) 621-8350",
        "linkedin_url": "https://www.linkedin.com/company/tag-trade-associates-group",
        "business_type": "Wholesaler",
        "source_platform": "US Trade Intelligence",
        "product": "Seasonal Metal Lanterns & Candelabras",
        "company_description": "Chicago-based wholesale supplier of seasonal metal candleholders, holiday candelabras, and tea light lanterns to 8,000+ US gift and home stores.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.93,
        "ai_reason": "Massive seasonal purchasing for autumn and holiday decor."
    },
    {
        "buyer_name": "Tim Torre",
        "company_name": "Torre & Tagus",
        "email": "procurement@torretagus.com",
        "website": "https://www.torretagus.com",
        "country": "USA",
        "phone": "+1 (800) 423-4417",
        "linkedin_url": "https://www.linkedin.com/company/torre-&-tagus",
        "business_type": "Distributor",
        "source_platform": "US Trade Registry",
        "product": "Contemporary Metal Candle Holders",
        "company_description": "Washington / BC distributor of contemporary tabletop accessories, geometric metal candleholders, and architectural glass/iron lanterns.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 90,
        "ai_confidence": 0.89,
        "ai_reason": "Modern design focus with high retail penetration."
    },
    {
        "buyer_name": "Mark Sullivan",
        "company_name": "Sullivan Gift & Home",
        "email": "buyers@sullivangift.com",
        "website": "https://www.sullivangift.com",
        "country": "USA",
        "phone": "+1 (800) 456-4568",
        "linkedin_url": "https://www.linkedin.com/company/sullivans-home-decor",
        "business_type": "Importer",
        "source_platform": "US Customs Manifest",
        "product": "Rustic Metal Candle Stands & Lanterns",
        "company_description": "Major US wholesaler and direct importer distributing rustic metal lanterns, candelabras, and holiday tabletop centerpieces across 50 states.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 96,
        "ai_confidence": 0.95,
        "ai_reason": "Established container-level buyer with 50-year track record."
    },
    {
        "buyer_name": "Jack Perez",
        "company_name": "Privilege International Inc",
        "email": "sales@privilege-inc.com",
        "website": "https://www.privilege-inc.com",
        "country": "USA",
        "phone": "+1 (888) 880-8789",
        "linkedin_url": "https://www.linkedin.com/company/privilege-international-inc",
        "business_type": "Importer",
        "source_platform": "US Trade Intelligence",
        "product": "Decorative Metal Lanterns & Votives",
        "company_description": "San Diego direct wholesale importer of decorative iron lanterns, votive sets, and rustic metal candleholders supplying major US department stores.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 93,
        "ai_confidence": 0.92,
        "ai_reason": "High turnover wholesale inventory for metal decor."
    },
    {
        "buyer_name": "Rajesh Sharma",
        "company_name": "Benzara Inc",
        "email": "procurement@benzara.com",
        "website": "https://www.benzara.com",
        "country": "USA",
        "phone": "+1 (909) 390-5800",
        "linkedin_url": "https://www.linkedin.com/company/benzara-inc",
        "business_type": "Importer",
        "source_platform": "US Trade Registry",
        "product": "Antique Bronze Candle Stands",
        "company_description": "Southern California importer and B2B drop-ship wholesaler of antique bronze candleholders, metal lanterns, and rustic Indian home accents.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 94,
        "ai_confidence": 0.93,
        "ai_reason": "Very familiar with Indian export packaging and lead times."
    },
    {
        "buyer_name": "Brian Elliott",
        "company_name": "Howard Elliott Collection",
        "email": "procurement@howardelliott.com",
        "website": "https://www.howardelliott.com",
        "country": "USA",
        "phone": "+1 (630) 871-1122",
        "linkedin_url": "https://www.linkedin.com/company/howard-elliott-collection",
        "business_type": "Distributor",
        "source_platform": "Apollo.io B2B",
        "product": "Metal Tabletop Candelabras",
        "company_description": "Chicago-area manufacturer and importer of decorative metal candle stands and tabletop centerpieces for hospitality and luxury residential projects.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 92,
        "ai_confidence": 0.91,
        "ai_reason": "Supplies luxury hotels and commercial decorators."
    },
    {
        "buyer_name": "Charles Peck",
        "company_name": "Trans-Ocean Imports",
        "email": "importing@transocean.com",
        "website": "https://www.transocean.com",
        "country": "USA",
        "phone": "+1 (914) 949-5656",
        "linkedin_url": "https://www.linkedin.com/company/trans-ocean-import-co-inc-",
        "business_type": "Importer",
        "source_platform": "US Trade Intelligence",
        "product": "Artisanal Metal Candle Accessories",
        "company_description": "New York direct importer of handcrafted home accents, metal accessories, and artisan textiles established in 1908.",
        "email_status": "VALID",
        "ai_priority": "HIGH",
        "ai_score": 91,
        "ai_confidence": 0.90,
        "ai_reason": "Financially stable century-old US import house."
    }
]
